### PR TITLE
Fixed trio inherited het + de novo rules.

### PR DESCRIPTION
**Pull request by brcopeland**
De novo flags are now fully used.  Inherited variant rule remains
unchanged.

### CODE REVIEW

**Comment by nickzren** [comment]
I have done some minor changes , please take a look when you have time , if things work as expected I will deploy to test out.

**Comment by nickzren** [comment]
Do we consider 'NEWLY HEMIZYGOUS' as high confidence denovo?

**Comment by nickzren** [comment]
I have updated denovo confidence rules.

**Comment by brcopeland** [comment]
Yeah I think your changes are good.  I like the new function for getting the de novo confidence; looks cleaner and more straightforward.

**Comment by nickzren** [comment]
I have done a further code changes after confirm the logic with you , can you double check the latest code?

**Comment by brcopeland** [comment]
Well, first of all I liked the previous function more.  It considered newly hemizygous variants as de novos, and the `isDenovo` variable at line 503 seems to accomplish nothing.  The code there will only be executed if one or the other variants is de novo, so that variable will always be `true`.

**Comment by nickzren** [comment]
"newly hemizygous" consider as 1 confidence .. and we only checked when confidence is 0 which is either 'Denovo' or 'Denovo; in ref' ... so i think previous code is redundant ..

**Pull request merged**
